name: gibMacOS Build

on:
  push:
    branches:
      - CI
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: 📥 Clone the repository
        uses: actions/checkout@v4

      - name: 🏗 Set up Python Virtual Environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip wheel

      - name: 📥 Download macOS Installer using gibMacOS
        run: |
          chmod +x gibMacOS.command
          ./gibMacOS.command -r

      - name: 🗂 Archive the macOS Installer
        run: |
          cd "macOS Downloads"
          tar -cvf macOS-installer.tar Install*

      - name: 🔪 Split the archive into 4GB parts
        run: |
          split -b 4G macOS Downloads/macOS-installer.tar macOS-part-

      - name: 📦 Upload the split parts as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macOS-Installer
          path: macOS-part-*

